services:
  mongodb:
    image: mongo:7.0
    container_name: shield-auth-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: