server:
  port: 8081

spring:

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAILTRAP_USER} # À récupérer sur ton compte Mailtrap-Connecte-toi sur Mailtrap.io.Va dans Email Testing > Inboxes.Clique sur "Show Credentials" et copie le username et le password.
    password: ${MAILTRAP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    name: auth-service
  data:
    mongodb:
      auto-index-creation: true # Force la création des index unique au démarrage
      uri: mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@localhost:27017/${MONGO_DB_NAME}?authSource=admin
rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

# Configuration sécurisée des logs
logging:
  level:
    org.springframework.security: DEBUG
    com.shield.auth_service: INFO

# Configuration du client Google- à partir de google console
google:
  client:
    id: ${GOOGLE_CLIENT_ID}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true